title: <a href="https://dmutako.github.io/data-science-final-project/" style="color:white;">Broad Trends in U.S. Broadband</a>
description: A closer look at the excuses for our slow internet :D
theme: jekyll-theme-cayman
